# This file will be used if we want to customize the Ruff configuration.
extend-exclude = ["*_pb2.py"]

[lint.isort]
force-single-line = true

[lint.per-file-ignores]
"src/ostorlab/configuration_manager.py" = ["UP045"]
"src/ostorlab/runtimes/local/services/mq.py" = ["UP045"]
"src/ostorlab/runtimes/runtime.py" = ["UP045"]
"src/ostorlab/runtimes/local/runtime.py" = ["UP045"]
