# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ostorlab/agent/message/proto/v3/fingerprint/ip/v4/service/x509/x509.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ostorlab.agent.message.proto.common.x509 import x509_pb2 as ostorlab_dot_agent_dot_message_dot_proto_dot_common_dot_x509_dot_x509__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nIostorlab/agent/message/proto/v3/fingerprint/ip/v4/service/x509/x509.proto\x12>ostorlab.agent.message.proto.v3.fingerprint.ip.v4.service.x509\x1a\x33ostorlab/agent/message/proto/common/x509/x509.proto\"\xb2\x01\n\x07Message\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04mask\x18\x02 \x01(\t\x12\x12\n\x07version\x18\x03 \x01(\x05:\x01\x34\x12\x0f\n\x07service\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\r\x12\x10\n\x08protocol\x18\x06 \x01(\t\x12\x46\n\ncert_chain\x18\x07 \x03(\x0b\x32\x32.ostorlab.agent.message.proto.common.x509.X509Cert')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ostorlab.agent.message.proto.v3.fingerprint.ip.v4.service.x509.x509_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=195
  _MESSAGE._serialized_end=373
# @@protoc_insertion_point(module_scope)
