# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aar.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='aar.proto',
    package='',
    syntax='proto2',
    serialized_pb=_b(
        '\n\taar.proto\"#\n\x03\x61\x61r\x12\x0f\n\x07scan_id\x18\x01 \x02(\x05\x12\x0b\n\x03url\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_AAR = _descriptor.Descriptor(
    name='aar',
    full_name='aar',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='scan_id', full_name='aar.scan_id', index=0,
            number=1, type=5, cpp_type=1, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='url', full_name='aar.url', index=1,
            number=2, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=13,
    serialized_end=48,
)

DESCRIPTOR.message_types_by_name['aar'] = _AAR

aar = _reflection.GeneratedProtocolMessageType('aar', (_message.Message,), dict(
    DESCRIPTOR=_AAR,
    __module__='aar_pb2'
    # @@protoc_insertion_point(class_scope:aar)
))
_sym_db.RegisterMessage(aar)

# @@protoc_insertion_point(module_scope)
