# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: macho.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='macho.proto',
    package='',
    serialized_pb=_b(
        '\n\x0bmacho.proto\"?\n\x05macho\x12\x0f\n\x07scan_id\x18\x01 \x02(\x05\x12\x10\n\x08\x66ilename\x18\x02 \x02(\t\x12\x13\n\x0b\x66ilecontent\x18\x03 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MACHO = _descriptor.Descriptor(
    name='macho',
    full_name='macho',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='scan_id', full_name='macho.scan_id', index=0,
            number=1, type=5, cpp_type=1, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='filename', full_name='macho.filename', index=1,
            number=2, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='filecontent', full_name='macho.filecontent', index=2,
            number=3, type=12, cpp_type=9, label=2,
            has_default_value=False, default_value=_b(""),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=15,
    serialized_end=78,
)

DESCRIPTOR.message_types_by_name['macho'] = _MACHO

macho = _reflection.GeneratedProtocolMessageType('macho', (_message.Message,), dict(
    DESCRIPTOR=_MACHO,
    __module__='macho_pb2'
    # @@protoc_insertion_point(class_scope:macho)
))
_sym_db.RegisterMessage(macho)

# @@protoc_insertion_point(module_scope)
