# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ostorlab/agent/message/proto/v3/capture/filesystem/filesystem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ostorlab/agent/message/proto/v3/capture/filesystem/filesystem.proto',
  package='ostorlab.agent.message.proto.v3.capture.filesystem',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\nCostorlab/agent/message/proto/v3/capture/filesystem/filesystem.proto\x12\x32ostorlab.agent.message.proto.v3.capture.filesystem\"\xb6\x01\n\x07Message\x12H\n\x05\x65vent\x18\x01 \x01(\x0e\x32\x39.ostorlab.agent.message.proto.v3.capture.filesystem.Event\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x05\x12\x0b\n\x03uid\x18\x04 \x01(\x05\x12\x0b\n\x03gid\x18\x05 \x01(\x05\x12\x0c\n\x04mode\x18\x06 \x01(\x05\x12\x0c\n\x04ppid\x18\x07 \x01(\x05\x12\x0c\n\x04proc\x18\x08 \x01(\t*\x96\x02\n\x05\x45vent\x12\n\n\x06\x41\x43\x43\x45SS\x10\x01\x12\x08\n\x04OPEN\x10\x02\x12\r\n\tOPEN_EXEC\x10\x03\x12\n\n\x06\x41TTRIB\x10\x04\x12\n\n\x06\x43REATE\x10\x05\x12\n\n\x06\x44\x45LETE\x10\x06\x12\x0f\n\x0b\x44\x45LETE_SELF\x10\x07\x12\x0e\n\nMOVED_FROM\x10\x08\x12\x0c\n\x08MOVED_TO\x10\t\x12\r\n\tMOVE_SELF\x10\n\x12\x0f\n\x0b\x43LOSE_WRITE\x10\x0b\x12\x11\n\rCLOSE_NOWRITE\x10\x0c\x12\x0e\n\nQ_OVERFLOW\x10\r\x12\x0f\n\x0b\x41\x43\x43\x45SS_PERM\x10\x0e\x12\r\n\tOPEN_PERM\x10\x0f\x12\x12\n\x0eOPEN_EXEC_PERM\x10\x10\x12\t\n\x05\x43LOSE\x10\x11\x12\x08\n\x04MOVE\x10\x12\x12\t\n\x05ONDIR\x10\x13')
)

_EVENT = _descriptor.EnumDescriptor(
  name='Event',
  full_name='ostorlab.agent.message.proto.v3.capture.filesystem.Event',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCESS', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN_EXEC', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ATTRIB', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE', index=4, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=5, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_SELF', index=6, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOVED_FROM', index=7, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOVED_TO', index=8, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOVE_SELF', index=9, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE_WRITE', index=10, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE_NOWRITE', index=11, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Q_OVERFLOW', index=12, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCESS_PERM', index=13, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN_PERM', index=14, number=15,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN_EXEC_PERM', index=15, number=16,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=16, number=17,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOVE', index=17, number=18,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONDIR', index=18, number=19,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=309,
  serialized_end=587,
)
_sym_db.RegisterEnumDescriptor(_EVENT)

Event = enum_type_wrapper.EnumTypeWrapper(_EVENT)
ACCESS = 1
OPEN = 2
OPEN_EXEC = 3
ATTRIB = 4
CREATE = 5
DELETE = 6
DELETE_SELF = 7
MOVED_FROM = 8
MOVED_TO = 9
MOVE_SELF = 10
CLOSE_WRITE = 11
CLOSE_NOWRITE = 12
Q_OVERFLOW = 13
ACCESS_PERM = 14
OPEN_PERM = 15
OPEN_EXEC_PERM = 16
CLOSE = 17
MOVE = 18
ONDIR = 19



_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='ostorlab.agent.message.proto.v3.capture.filesystem.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='ostorlab.agent.message.proto.v3.capture.filesystem.Message.event', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='ostorlab.agent.message.proto.v3.capture.filesystem.Message.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='ostorlab.agent.message.proto.v3.capture.filesystem.Message.pid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='ostorlab.agent.message.proto.v3.capture.filesystem.Message.uid', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gid', full_name='ostorlab.agent.message.proto.v3.capture.filesystem.Message.gid', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='ostorlab.agent.message.proto.v3.capture.filesystem.Message.mode', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ppid', full_name='ostorlab.agent.message.proto.v3.capture.filesystem.Message.ppid', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proc', full_name='ostorlab.agent.message.proto.v3.capture.filesystem.Message.proc', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=306,
)

_MESSAGE.fields_by_name['event'].enum_type = _EVENT
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.enum_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'ostorlab.agent.message.proto.v3.capture.filesystem.filesystem_pb2'
  # @@protoc_insertion_point(class_scope:ostorlab.agent.message.proto.v3.capture.filesystem.Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
