# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ostorlab/agent/message/proto/v3/scan/file/ios.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ostorlab/agent/message/proto/v3/scan/file/ios.proto',
  package='ostorlab.agent.message.proto.v3.scan.file',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3ostorlab/agent/message/proto/v3/scan/file/ios.proto\x12)ostorlab.agent.message.proto.v3.scan.file\"I\n\x03ios\x12\x0f\n\x07scan_id\x18\x01 \x01(\x05\x12\x0c\n\x04\x66ile\x18\x02 \x01(\x0c\x12\x0c\n\x04hash\x18\x03 \x01(\t\x12\x15\n\x08platform\x18\x04 \x01(\t:\x03ios'
)




_IOS = _descriptor.Descriptor(
  name='ios',
  full_name='ostorlab.agent.message.proto.v3.scan.file.ios',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scan_id', full_name='ostorlab.agent.message.proto.v3.scan.file.ios.scan_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='ostorlab.agent.message.proto.v3.scan.file.ios.file', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='ostorlab.agent.message.proto.v3.scan.file.ios.hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='platform', full_name='ostorlab.agent.message.proto.v3.scan.file.ios.platform', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"ios".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=171,
)

DESCRIPTOR.message_types_by_name['ios'] = _IOS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ios = _reflection.GeneratedProtocolMessageType('ios', (_message.Message,), {
  'DESCRIPTOR' : _IOS,
  '__module__' : 'ostorlab.agent.message.proto.v3.scan.file.ios_pb2'
  # @@protoc_insertion_point(class_scope:ostorlab.agent.message.proto.v3.scan.file.ios)
  })
_sym_db.RegisterMessage(ios)


# @@protoc_insertion_point(module_scope)
