# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ticket.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cticket.proto\x12-ostorlab.agent.message.proto.v3.report.ticket\"+\n\x08\x43omments\x12\x0e\n\x06\x61uthor\x18\x01 \x02(\t\x12\x0f\n\x07message\x18\x02 \x02(\t\"\x9f\x01\n\x07Message\x12\x11\n\tticket_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x02(\t\x12I\n\x08\x63omments\x18\x04 \x03(\x0b\x32\x37.ostorlab.agent.message.proto.v3.report.ticket.Comments\x12\x12\n\nticket_key\x18\x05 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ticket_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMENTS._serialized_start=63
  _COMMENTS._serialized_end=106
  _MESSAGE._serialized_start=109
  _MESSAGE._serialized_end=268
# @@protoc_insertion_point(module_scope)
