# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/scan.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='v2/scan.proto',
    package='',
    serialized_pb=_b('\n\rv2/scan.proto\"\x17\n\x04scan\x12\x0f\n\x07scan_id\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SCAN = _descriptor.Descriptor(
    name='scan',
    full_name='scan',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='scan_id', full_name='scan.scan_id', index=0,
            number=1, type=5, cpp_type=1, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=17,
    serialized_end=40,
)

DESCRIPTOR.message_types_by_name['scan'] = _SCAN

scan = _reflection.GeneratedProtocolMessageType('scan', (_message.Message,), dict(
    DESCRIPTOR=_SCAN,
    __module__='v2.scan_pb2'
    # @@protoc_insertion_point(class_scope:scan)
))
_sym_db.RegisterMessage(scan)

# @@protoc_insertion_point(module_scope)
