# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ostorlab/agent/message/proto/v3/asset/store/android_store/developer/developer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ostorlab/agent/message/proto/v3/asset/store/android_store/developer/developer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nSostorlab/agent/message/proto/v3/asset/store/android_store/developer/developer.proto\x12\x43ostorlab.agent.message.proto.v3.asset.store.android_store.developer\"b\n\x07Message\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\x12\x11\n\tdeveloper\x18\x02 \x01(\t\x12\x15\n\rdeveloper_url\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x65veloper_email\x18\x04 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ostorlab.agent.message.proto.v3.asset.store.android_store.developer.developer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=156
  _globals['_MESSAGE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
