# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post_scan_done_timeout.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='post_scan_done_timeout.proto',
  package='v3.report.event',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1cpost_scan_done_timeout.proto\x12\x0fv3.report.event\"\x1e\n\x07Message\x12\x13\n\x0btimeout_sec\x18\x01 \x02(\x02')
)




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='v3.report.event.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeout_sec', full_name='v3.report.event.Message.timeout_sec', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'post_scan_done_timeout_pb2'
  # @@protoc_insertion_point(class_scope:v3.report.event.Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
