# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ostorlab/agent/message/proto/v3/asset/file/api_schema/wsdl/wsdl.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ostorlab/agent/message/proto/v3/asset/file/api_schema/wsdl/wsdl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEostorlab/agent/message/proto/v3/asset/file/api_schema/wsdl/wsdl.proto\x12:ostorlab.agent.message.proto.v3.asset.file.api_schema.wsdl\"\'\n\x0f\x41ndroidMetadata\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\" \n\x0bIOSMetadata\x12\x11\n\tbundle_id\x18\x01 \x01(\t\"%\n\x06Header\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xa5\x03\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x13\n\x0b\x63ontent_url\x18\x03 \x01(\t\x12g\n\x10\x61ndroid_metadata\x18\x04 \x01(\x0b\x32K.ostorlab.agent.message.proto.v3.asset.file.api_schema.wsdl.AndroidMetadataH\x00\x12_\n\x0cios_metadata\x18\x05 \x01(\x0b\x32G.ostorlab.agent.message.proto.v3.asset.file.api_schema.wsdl.IOSMetadataH\x00\x12\x14\n\x0c\x65ndpoint_url\x18\x06 \x01(\t\x12\x19\n\x0bschema_type\x18\x07 \x01(\t:\x04wsdl\x12Y\n\rextra_headers\x18\x08 \x03(\x0b\x32\x42.ostorlab.agent.message.proto.v3.asset.file.api_schema.wsdl.HeaderB\x10\n\x0emetadata_oneof')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ostorlab.agent.message.proto.v3.asset.file.api_schema.wsdl.wsdl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANDROIDMETADATA']._serialized_start=133
  _globals['_ANDROIDMETADATA']._serialized_end=172
  _globals['_IOSMETADATA']._serialized_start=174
  _globals['_IOSMETADATA']._serialized_end=206
  _globals['_HEADER']._serialized_start=208
  _globals['_HEADER']._serialized_end=245
  _globals['_MESSAGE']._serialized_start=248
  _globals['_MESSAGE']._serialized_end=669
# @@protoc_insertion_point(module_scope)
