# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apk/apk.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rapk/apk.proto\x12\x38ostorlab.agent.message.proto.v3.asset.file.harmonyos.apk\"\'\n\x0f\x41ndroidMetadata\x12\x14\n\x0cpackage_name\x18\x01 \x01(\t\" \n\x0bIOSMetadata\x12\x11\n\tbundle_id\x18\x01 \x01(\t\"&\n\x11HarmonyOSMetadata\x12\x11\n\tbundle_id\x18\x01 \x01(\t\"\x80\x03\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x13\n\x0b\x63ontent_url\x18\x03 \x01(\t\x12\x65\n\x10\x61ndroid_metadata\x18\x04 \x01(\x0b\x32I.ostorlab.agent.message.proto.v3.asset.file.harmonyos.apk.AndroidMetadataH\x00\x12]\n\x0cios_metadata\x18\x05 \x01(\x0b\x32\x45.ostorlab.agent.message.proto.v3.asset.file.harmonyos.apk.IOSMetadataH\x00\x12i\n\x12harmonyos_metadata\x18\x06 \x01(\x0b\x32K.ostorlab.agent.message.proto.v3.asset.file.harmonyos.apk.HarmonyOSMetadataH\x00\x42\x10\n\x0emetadata_oneof')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apk.apk_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANDROIDMETADATA._serialized_start=75
  _ANDROIDMETADATA._serialized_end=114
  _IOSMETADATA._serialized_start=116
  _IOSMETADATA._serialized_end=148
  _HARMONYOSMETADATA._serialized_start=150
  _HARMONYOSMETADATA._serialized_end=188
  _MESSAGE._serialized_start=191
  _MESSAGE._serialized_end=575
# @@protoc_insertion_point(module_scope)
