# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ostorlab/agent/message/proto/v3/scan/web.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ostorlab/agent/message/proto/v3/scan/web.proto',
  package='ostorlab.agent.message.proto.v3.scan',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.ostorlab/agent/message/proto/v3/scan/web.proto\x12$ostorlab.agent.message.proto.v3.scan\"j\n\x03web\x12\x0f\n\x07scan_id\x18\x01 \x01(\x05\x12;\n\x04urls\x18\x02 \x03(\x0b\x32-.ostorlab.agent.message.proto.v3.scan.web.url\x1a\x15\n\x03url\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t'
)




_WEB_URL = _descriptor.Descriptor(
  name='url',
  full_name='ostorlab.agent.message.proto.v3.scan.web.url',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='ostorlab.agent.message.proto.v3.scan.web.url.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=194,
)

_WEB = _descriptor.Descriptor(
  name='web',
  full_name='ostorlab.agent.message.proto.v3.scan.web',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scan_id', full_name='ostorlab.agent.message.proto.v3.scan.web.scan_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='urls', full_name='ostorlab.agent.message.proto.v3.scan.web.urls', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_WEB_URL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=194,
)

_WEB_URL.containing_type = _WEB
_WEB.fields_by_name['urls'].message_type = _WEB_URL
DESCRIPTOR.message_types_by_name['web'] = _WEB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

web = _reflection.GeneratedProtocolMessageType('web', (_message.Message,), {

  'url' : _reflection.GeneratedProtocolMessageType('url', (_message.Message,), {
    'DESCRIPTOR' : _WEB_URL,
    '__module__' : 'ostorlab.agent.message.proto.v3.scan.web_pb2'
    # @@protoc_insertion_point(class_scope:ostorlab.agent.message.proto.v3.scan.web.url)
    })
  ,
  'DESCRIPTOR' : _WEB,
  '__module__' : 'ostorlab.agent.message.proto.v3.scan.web_pb2'
  # @@protoc_insertion_point(class_scope:ostorlab.agent.message.proto.v3.scan.web)
  })
_sym_db.RegisterMessage(web)
_sym_db.RegisterMessage(web.url)


# @@protoc_insertion_point(module_scope)
