# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ostorlab/agent/message/proto/v3/device/monitor_filesystem.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ostorlab/agent/message/proto/v3/device/monitor_filesystem.proto',
  package='ostorlab.agent.message.proto.v3.device',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n?ostorlab/agent/message/proto/v3/device/monitor_filesystem.proto\x12&ostorlab.agent.message.proto.v3.device\"\xd4\x01\n\x12monitor_filesystem\x12\x0f\n\x07scan_id\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x05\x12\x0b\n\x03uid\x18\x04 \x01(\x05\x12\x0b\n\x03gid\x18\x05 \x01(\x05\x12\x0c\n\x04mode\x18\x06 \x01(\x05\x12\x0c\n\x04ppid\x18\x07 \x01(\x05\x12\x0c\n\x04proc\x18\x08 \x01(\t\x12\x0c\n\x04type\x18\t \x01(\t\x12\x12\n\nuser_right\x18\n \x01(\t\x12\x13\n\x0bgroup_right\x18\x0b \x01(\t\x12\x13\n\x0bother_right\x18\x0c \x01(\t'
)




_MONITOR_FILESYSTEM = _descriptor.Descriptor(
  name='monitor_filesystem',
  full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scan_id', full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem.scan_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filename', full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pid', full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem.pid', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uid', full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem.uid', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gid', full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem.gid', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem.mode', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ppid', full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem.ppid', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proc', full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem.proc', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem.type', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_right', full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem.user_right', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='group_right', full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem.group_right', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='other_right', full_name='ostorlab.agent.message.proto.v3.device.monitor_filesystem.other_right', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=320,
)

DESCRIPTOR.message_types_by_name['monitor_filesystem'] = _MONITOR_FILESYSTEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

monitor_filesystem = _reflection.GeneratedProtocolMessageType('monitor_filesystem', (_message.Message,), {
  'DESCRIPTOR' : _MONITOR_FILESYSTEM,
  '__module__' : 'ostorlab.agent.message.proto.v3.device.monitor_filesystem_pb2'
  # @@protoc_insertion_point(class_scope:ostorlab.agent.message.proto.v3.device.monitor_filesystem)
  })
_sym_db.RegisterMessage(monitor_filesystem)


# @@protoc_insertion_point(module_scope)
