# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ostorlab/agent/message/proto/v3/fingerprint/file/ios/metadata/metadata.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ostorlab/agent/message/proto/v3/fingerprint/file/ios/metadata/metadata.proto',
  package='ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nLostorlab/agent/message/proto/v3/fingerprint/file/ios/metadata/metadata.proto\x12=ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata\"5\n\nPermission\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x11usage_description\x18\x02 \x01(\t\"|\n\x07Message\x12\x11\n\tbundle_id\x18\x01 \x01(\t\x12^\n\x0bpermissions\x18\x02 \x03(\x0b\x32I.ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata.Permission'
)




_PERMISSION = _descriptor.Descriptor(
  name='Permission',
  full_name='ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata.Permission',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata.Permission.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='usage_description', full_name='ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata.Permission.usage_description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=196,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bundle_id', full_name='ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata.Message.bundle_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='permissions', full_name='ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata.Message.permissions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=322,
)

_MESSAGE.fields_by_name['permissions'].message_type = _PERMISSION
DESCRIPTOR.message_types_by_name['Permission'] = _PERMISSION
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Permission = _reflection.GeneratedProtocolMessageType('Permission', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSION,
  '__module__' : 'ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata.metadata_pb2'
  # @@protoc_insertion_point(class_scope:ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata.Permission)
  })
_sym_db.RegisterMessage(Permission)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata.metadata_pb2'
  # @@protoc_insertion_point(class_scope:ostorlab.agent.message.proto.v3.fingerprint.file.ios.metadata.Message)
  })
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
