# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: android_logs.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='android_logs.proto',
    package='',
    serialized_pb=_b(
        '\n\x12\x61ndroid_logs.proto\"R\n\x0c\x61ndroid_logs\x12\x0f\n\x07scan_id\x18\x01 \x02(\x05\x12\x11\n\ttimestamp\x18\x02 \x02(\x02\x12\r\n\x05level\x18\x03 \x02(\t\x12\x0f\n\x07message\x18\x04 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ANDROID_LOGS = _descriptor.Descriptor(
    name='android_logs',
    full_name='android_logs',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='scan_id', full_name='android_logs.scan_id', index=0,
            number=1, type=5, cpp_type=1, label=2,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='timestamp', full_name='android_logs.timestamp', index=1,
            number=2, type=2, cpp_type=6, label=2,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='level', full_name='android_logs.level', index=2,
            number=3, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='message', full_name='android_logs.message', index=3,
            number=4, type=9, cpp_type=9, label=2,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=22,
    serialized_end=104,
)

DESCRIPTOR.message_types_by_name['android_logs'] = _ANDROID_LOGS

android_logs = _reflection.GeneratedProtocolMessageType('android_logs', (_message.Message,), dict(
    DESCRIPTOR=_ANDROID_LOGS,
    __module__='android_logs_pb2'
    # @@protoc_insertion_point(class_scope:android_logs)
))
_sym_db.RegisterMessage(android_logs)

# @@protoc_insertion_point(module_scope)
