on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: ['macos-latest']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install .[scanner]
        pip install .[agent]
        pip install .[serve]

    - name: Create DMG file
    - run: |
        hdiutil create -fs HFS+ -format UDRW -srcfolder . oxo.dmg
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: oxo.dmg