# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ostorlab/scanner/proto/assets/asset_group.proto
# Protobuf Python Version: 6.33.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    6,
    '',
    'ostorlab/scanner/proto/assets/asset_group.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ostorlab.scanner.proto.assets import file_pb2 as ostorlab_dot_scanner_dot_proto_dot_assets_dot_file__pb2
from ostorlab.scanner.proto.assets import apk_pb2 as ostorlab_dot_scanner_dot_proto_dot_assets_dot_apk__pb2
from ostorlab.scanner.proto.assets import aab_pb2 as ostorlab_dot_scanner_dot_proto_dot_assets_dot_aab__pb2
from ostorlab.scanner.proto.assets import ipa_pb2 as ostorlab_dot_scanner_dot_proto_dot_assets_dot_ipa__pb2
from ostorlab.scanner.proto.assets import repository_pb2 as ostorlab_dot_scanner_dot_proto_dot_assets_dot_repository__pb2
from ostorlab.scanner.proto.assets import repository_archive_pb2 as ostorlab_dot_scanner_dot_proto_dot_assets_dot_repository__archive__pb2
from ostorlab.scanner.proto.assets import link_pb2 as ostorlab_dot_scanner_dot_proto_dot_assets_dot_link__pb2
from ostorlab.scanner.proto.assets import network_pb2 as ostorlab_dot_scanner_dot_proto_dot_assets_dot_network__pb2
from ostorlab.scanner.proto.assets import ip_pb2 as ostorlab_dot_scanner_dot_proto_dot_assets_dot_ip__pb2
from ostorlab.scanner.proto.assets import v4_pb2 as ostorlab_dot_scanner_dot_proto_dot_assets_dot_v4__pb2
from ostorlab.scanner.proto.assets import v6_pb2 as ostorlab_dot_scanner_dot_proto_dot_assets_dot_v6__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/ostorlab/scanner/proto/assets/asset_group.proto\x12)ostorlab.scanner.proto.assets.asset_group\x1a(ostorlab/scanner/proto/assets/file.proto\x1a\'ostorlab/scanner/proto/assets/apk.proto\x1a\'ostorlab/scanner/proto/assets/aab.proto\x1a\'ostorlab/scanner/proto/assets/ipa.proto\x1a.ostorlab/scanner/proto/assets/repository.proto\x1a\x36ostorlab/scanner/proto/assets/repository_archive.proto\x1a(ostorlab/scanner/proto/assets/link.proto\x1a+ostorlab/scanner/proto/assets/network.proto\x1a&ostorlab/scanner/proto/assets/ip.proto\x1a&ostorlab/scanner/proto/assets/v4.proto\x1a&ostorlab/scanner/proto/assets/v6.proto\"\xce\x05\n\x07Message\x12:\n\x05\x66iles\x18\x01 \x03(\x0b\x32+.ostorlab.scanner.proto.assets.file.Message\x12?\n\x0b\x61ndroid_apk\x18\x04 \x03(\x0b\x32*.ostorlab.scanner.proto.assets.apk.Message\x12?\n\x0b\x61ndroid_aab\x18\x05 \x03(\x0b\x32*.ostorlab.scanner.proto.assets.aab.Message\x12;\n\x07ios_ipa\x18\x06 \x03(\x0b\x32*.ostorlab.scanner.proto.assets.ipa.Message\x12G\n\x0crepositories\x18\x07 \x03(\x0b\x32\x31.ostorlab.scanner.proto.assets.repository.Message\x12V\n\x13repository_archives\x18\x08 \x03(\x0b\x32\x39.ostorlab.scanner.proto.assets.repository_archive.Message\x12\x39\n\x04urls\x18\t \x03(\x0b\x32+.ostorlab.scanner.proto.assets.link.Message\x12@\n\x08networks\x18\n \x03(\x0b\x32..ostorlab.scanner.proto.assets.network.Message\x12\x36\n\x03ips\x18\x0b \x03(\x0b\x32).ostorlab.scanner.proto.assets.ip.Message\x12\x38\n\x05ipv4s\x18\x0c \x03(\x0b\x32).ostorlab.scanner.proto.assets.v4.Message\x12\x38\n\x05ipv6s\x18\r \x03(\x0b\x32).ostorlab.scanner.proto.assets.v6.Message')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ostorlab.scanner.proto.assets.asset_group_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=571
  _globals['_MESSAGE']._serialized_end=1289
# @@protoc_insertion_point(module_scope)
