# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ostorlab/scanner/proto/assets/repository.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ostorlab/scanner/proto/assets/repository.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.ostorlab/scanner/proto/assets/repository.proto\x12(ostorlab.scanner.proto.assets.repository\"\xe0\x01\n\x07Message\x12\x16\n\x0erepository_url\x18\x01 \x01(\t\x12\x13\n\x0b\x63ommit_hash\x18\x02 \x01(\t\x12L\n\x08provider\x18\x03 \x01(\x0e\x32:.ostorlab.scanner.proto.assets.repository.Message.Provider\x12\x13\n\x0b\x63ontent_url\x18\x04 \x01(\t\"E\n\x08Provider\x12\n\n\x06GITHUB\x10\x00\x12\n\n\x06GITLAB\x10\x01\x12\t\n\x05\x41ZURE\x10\x02\x12\r\n\tBITBUCKET\x10\x03\x12\x07\n\x03GIT\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ostorlab.scanner.proto.assets.repository_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=93
  _globals['_MESSAGE']._serialized_end=317
  _globals['_MESSAGE_PROVIDER']._serialized_start=248
  _globals['_MESSAGE_PROVIDER']._serialized_end=317
# @@protoc_insertion_point(module_scope)
